version: '2.3'

services:

  desktop:
    image: dorowu/ubuntu-desktop-lxde-vnc:bionic
    shm_size: 6gb
    runtime: nvidia
    restart: always
    environment:
      - VNC_PASSWORD=
      - HTTP_PASSWORD=
      - USER=cloud-computer
      - PASSWORD=password
    expose:
      - 80
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:desktop.$CLOUD_COMPUTER_HOST_DNS
      - traefik.port=80
    volumes:
      - CLOUD_COMPUTER_REPOSITORY:$CLOUD_COMPUTER_REPOSITORY
      - CLOUD_COMPUTER_TMUX:$CLOUD_COMPUTER_TMUX
      - CLOUD_COMPUTER_X11:$CLOUD_COMPUTER_X11

volumes:
  CLOUD_COMPUTER_REPOSITORY:
  CLOUD_COMPUTER_TMUX:
  CLOUD_COMPUTER_X11:
