FROM node:10.16.0-alpine

ARG REACT_APP
ENV REACT_APP=$REACT_APP

ARG REACT_APP_HOST
ENV REACT_APP_HOST=$REACT_APP_HOST

ARG REACT_APP_WEBSOCKET_HOST
ENV REACT_APP_WEBSOCKET_HOST=$REACT_APP_WEBSOCKET_HOST

ARG AUTH_SERVICE_HOST
ENV AUTH_SERVICE_HOST=$AUTH_SERVICE_HOST

ARG STREAM_HOST
ENV STREAM_HOST=$STREAM_HOST

# Setting working directory. All the path will be relative to WORKDIR
WORKDIR /usr/src/app

# Installing dependencies
COPY package*.json ./
RUN npm install

# Copying source files
COPY . .

# Building app
# RUN npm run build

# Expose
EXPOSE 9998

# Running the app
CMD [ "npm", "run", "dev" ]
