FROM node:10.16.0-alpine

# Setting working directory. All the path will be relative to WORKDIR
WORKDIR /usr/src/app

# Installing dependencies
COPY package*.json ./
RUN npm install

# Copying source files
COPY . .

# Building app
RUN npm run build

# Expose
EXPOSE 9998

# Running the app
CMD [ "npm", "start" ]
