# Export cloud computer shell environment
eval "$(yarn --cwd ../cloud-computer environment)"

CLOUD_COMPUTER_DNS_DOMAIN=${CLOUD_COMPUTER_DNS_DOMAIN-cloud-computer.dev}
CLOUD_COMPUTER_DNS_TOKEN=${CLOUD_COMPUTER_DNS_TOKEN-}
CLOUD_COMPUTER_DNS_ZONE=${CLOUD_COMPUTER_DNS_ZONE-}

echo export CLOUD_COMPUTER_DNS_DOMAIN=$CLOUD_COMPUTER_DNS_DOMAIN
echo export CLOUD_COMPUTER_DNS_TOKEN=$CLOUD_COMPUTER_DNS_TOKEN
echo export CLOUD_COMPUTER_DNS_ZONE=$CLOUD_COMPUTER_DNS_ZONE
echo export CLOUD_COMPUTER_DNS_NAME=$CLOUD_COMPUTER_HOST_ID.$CLOUD_COMPUTER_DNS_DOMAIN
