FROM node:10.16.0-alpine

### Create directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

### Copy package.json
COPY package.json .
RUN npm install
RUN npm install -g nodemon

### Copy all files
COPY . .

### Expose default port
EXPOSE 3000

CMD ["npm", "run", "start.dev"]