FROM node:10.16.0-alpine

RUN npm config set unsafe-perm true

### Create directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

### Copy package.json
COPY package.json .
RUN npm install

### Copy all files
COPY . .

### Expose default port
EXPOSE 3000

CMD ["npm", "run", "start"]
